[workspace]
members = [
    "crates/nerv-cli",
    "crates/nerv-jit",
    "crates/nerv-lexer",
    "crates/nerv-runtime",
    "crates/nerv-sema",
    "crates/nerv-syntax",
]
exclude = ["old/rust-test"]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.94"
license = "MIT"

[workspace.dependencies]
logos = "=0.16.1"
llvm-sys = "=231.0.0"
